#!/usr/bin/env python3
"""Write docs/EDGE_QUALITY_REPORT.md: per relationship type, counts and a seeded random sample of
edges with their quotes and a blank 'correct?' column for a human reviewer. Nothing is auto-judged."""
from __future__ import annotations

import json
import random
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
state = json.loads((ROOT / "data" / "knowledge" / "knowledge_state.json").read_text(encoding="utf-8"))
ent = {e["id"]: e for e in state["entities"]}
SKIP = {"AUTHORED_BY", "CITES", "SHARES_REFERENCES"}  # deterministic metadata, not judgement calls
rng = random.Random(7)
by_rel: dict[str, list] = {}
for r in state["relationships"]:
    if r["relation"] not in SKIP:
        by_rel.setdefault(r["relation"], []).append(r)
lines = ["# Edge quality review sheet", "",
         "Generated by `scripts/edge_quality_report.py` (seed 7). **Nothing here is auto-judged.** Fill the *correct?* column "
         "(y / n) by reading each quote, then compute precision per relation yourself. Edges you mark `n` show which rule or "
         "alias needs tightening in `src/modeling/ontology.py`.", ""]
for rel, items in sorted(by_rel.items()):
    conf = Counter(i["confidence"] for i in items)
    lines += [f"## {rel}  ({len(items)} edges; {dict(conf)})", "",
              "| id | source | target | conf | rule | quote | correct? |", "|---|---|---|---|---|---|---|"]
    for r in rng.sample(items, min(20, len(items))):
        q = r["evidence"].replace("|", "/").replace("\n", " ")[:220]
        lines.append(f"| {r['id']} | {ent[r['source']]['name'][:34]} | {ent[r['target']]['name'][:34]} | {r['confidence']} | {r['rule']} | {q} |  |")
    lines.append("")
out = ROOT / "docs" / "EDGE_QUALITY_REPORT.md"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out.relative_to(ROOT)} ({sum(min(20, len(v)) for v in by_rel.values())} sampled edges)")
